# Collaborators can publish a new version **of what's on master** by leaving a review on any PR, generally the PR that just closed.
# To trigger this, the comment must match the format `🚀 version`, where "version" is anything accepted by `npm version XXX`

name: Publish

on:
  - push

jobs:

  npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm whoami
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
